// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ephemeroi-combined/Council.tsx": () => import("../components/mockups/ephemeroi-combined/Council.tsx"),
  "./components/mockups/ephemeroi-combined/Manuscript.tsx": () => import("../components/mockups/ephemeroi-combined/Manuscript.tsx"),
  "./components/mockups/ephemeroi-combined/Observatory.tsx": () => import("../components/mockups/ephemeroi-combined/Observatory.tsx")
};
